ADM:
    Info:
        name: 'info'

<Info>:
    BoxLayout:
        orientation: 'vertical'
        Date:
            id: date
            font_size: '50sp'
        Label:
            text: 'Jonuary: 1 2 3 4 5 6 7 8 9'
            font_size: '35sp'
        Label:
            text: 'Matthewer: 1 2 3 4 5 6 7 8 9'
            font_size: '35sp'
        Label:
            text: 'Alicer: 1 2 3 4 5 6 7 8 9'
            font_size: '35sp'